// Todas as janelas (popups) do sistema que abrem pelo useRetorno().modal — o levantamento de 02/10/2026. Cada uma com
// o desenho parado e o ▶ que abre a janela de verdade. As janelas próprias (Interromper, Pedir documentos, Janela da
// empresa…) ficam em pecas.tsx.
import { janela } from './pecas';
import { CONCILIA, EXECUTOR } from './telas';
import type { Peca } from './tipos';

const SAIR = [{ rotulo: 'Voltar' }] as const;
const IMPORTAR = () => [{ rotulo: 'Cancelar' }, { rotulo: 'Sobrepor o movimento', variante: 'btn-danger' as const }, { rotulo: 'Importar apenas novas', variante: 'btn-primary' as const }];

export const JANELAS: Peca[] = [
  // Tarefas › Executor
  janela('jn-nao-se-aplica', 'Não se aplica? (saída da etapa)', EXECUTOR, { icone: 'checkCircle', titulo: 'Não se aplica?', html: 'Contabilização da Folha: "A empresa não tem funcionários". A etapa conta como concluída nesta competência.', botoes: [...SAIR, { rotulo: 'Não se aplica', variante: 'btn-primary' }] }),
  // Tarefas › Cadastro
  janela('jn-excluir-conta', 'Excluir esta conta? (Cadastro › Contas bancárias)', ['t-cadastro-janela'], { icone: 'alert', titulo: 'Excluir esta conta?', texto: 'Sicoob · Ag. 3144-5 · C/C 52.166-3. Excluir é para conta cadastrada por engano; a conta que deixou de ser usada se encerra.', botoes: [...SAIR, { rotulo: 'Excluir', variante: 'btn-danger' }] }),
  janela('jn-importar-plano', 'Importar o plano de contas? (Cadastro › Plano)', ['t-cadastro-janela'], { icone: 'upload', titulo: 'Importar o plano de contas?', html: '<b>412 contas</b>: 412 novas.<br>O balancete serve como plano: as contas dele viram o plano da empresa.', botoes: [...SAIR, { rotulo: 'Importar', variante: 'btn-primary' }] }),
  janela('jn-desativar', 'Desativar a pessoa? (Cadastro › Usuários)', ['t-cadastro'], { icone: 'alert', titulo: 'Desativar Clara?', texto: 'A conta deixa de entrar no nads e no Entregas. Dá para reativar depois.', botoes: [...SAIR, { rotulo: 'Desativar', variante: 'btn-danger' }] }),
  janela('jn-protecao', 'Ligar a proteção do login? (Cadastro › Configurações)', ['t-cadastro-config'], { icone: 'lock', titulo: 'Ligar a proteção do login?', texto: 'Quem não é administrador e ainda não foi liberado vai precisar do código para entrar neste computador.', botoes: [...SAIR, { rotulo: 'Ligar', variante: 'btn-primary' }] }),
  // Tarefas › Drive
  janela('jn-propriedades', 'Propriedades (Drive)', ['t-drive'], { icone: 'fileText', titulo: 'Propriedades de extrato-agosto.pdf', html: 'Tipo: PDF · Tamanho: 182 KB<br>Pasta: 292 › 2026 › Bancos', botoes: [{ rotulo: 'OK', variante: 'btn-primary' }] }),
  // Extratudo › Extrator
  janela('jn-como-importar', 'Como importar o extrato / o razão?', ['e-importacao', 't-exec-importacao', 't-exec-cheque'], { icone: 'upload', titulo: 'Como importar o razão?', html: 'Já existem <b>171 lançamento(s)</b> nas datas destes arquivos; os arquivos são 1.<br><br><b>Importar apenas novas</b> — mantém o que já está guardado e só acrescenta o que ainda não existe.<br><b>Sobrepor o movimento</b> — apaga o que está guardado nessas datas e fica com o que veio nos arquivos.', botoes: IMPORTAR() }),
  janela('jn-remover-todos', 'Remover todos? (Em lote)', ['e-importacao', 't-exec-importacao'], { icone: 'alert', titulo: 'Remover todos?', html: 'O razão do <b>Sicoob</b> nos 8 meses do período. Dá para importar de novo depois.', botoes: [...SAIR, { rotulo: 'Remover todos', variante: 'btn-danger' }] }),
  janela('jn-excluir-arquivo', 'Excluir este arquivo? (Extrator › Arquivos)', ['e-arquivos'], { icone: 'alert', titulo: 'Excluir este arquivo?', html: 'Os <b>171 lançamento(s)</b> de <b>extrato-agosto.pdf</b> saem da conferência.', botoes: [...SAIR, { rotulo: 'Excluir', variante: 'btn-danger' }] }),
  janela('jn-falta-extrato', 'Falta o extrato do banco (aba travada)', ['e-arquivos', 'e-conferencia'], { icone: 'upload', titulo: 'Falta o extrato do banco', html: 'Importe os extratos bancários (PDF) para conferir.', botoes: [{ rotulo: 'Agora não' }, { rotulo: 'Importar extrato', variante: 'btn-primary' }] }),
  janela('jn-cancelar-creditor', 'Cancelar a conciliação? (Creditor)', ['e-creditor'], { icone: 'alert', titulo: 'Cancelar a conciliação?', texto: 'O relatório lido e as decisões serão descartados.', botoes: [...SAIR, { rotulo: 'Cancelar tudo', variante: 'btn-primary' }] }),
  // Concilia aí
  janela('jn-boas-vindas', 'Seja bem-vindo(a) ao Concilia aí! (presta serviços?)', CONCILIA, { icone: 'briefcase', titulo: 'Seja bem-vindo(a) ao Concilia aí!', html: 'Antes de começar: a empresa <b>292 — FITO INDUSTRIA E COMERCIO DE ALIMENTOS LTDA</b> presta serviços?', botoes: [{ rotulo: 'Não' }, { rotulo: 'Sim', variante: 'btn-primary' }], obrigatoria: true }),
  janela('jn-nao-importadas', 'Entradas ainda não importadas (aba travada)', CONCILIA, { icone: 'upload', titulo: 'Entradas ainda não importadas', texto: 'Importe o relatório de entradas para ver esta página.', botoes: [{ rotulo: 'Agora não' }, { rotulo: 'Importar entradas', variante: 'btn-primary' }] }),
  janela('jn-outra-empresa', 'Esse balancete parece ser de outra empresa', ['c-importacao', 't-exec-importacao'], { icone: 'alert', titulo: 'Esse balancete parece ser de outra empresa', html: '• O nome no arquivo é outro.<br>• As contas não batem com o cadastro.', botoes: [{ rotulo: 'Cancelar importação' }, { rotulo: 'Importar mesmo assim', variante: 'btn-danger' }] }),
  janela('jn-como-importar-notas', 'Como importar as entradas/saídas/serviços?', ['c-importacao', 't-exec-importacao'], { icone: 'upload', titulo: 'Como importar as entradas?', html: 'Já existem <b>462 nota(s)</b> nesse período.', botoes: IMPORTAR() }),
  janela('jn-apagar-balancete', 'Apagar o balancete? / Apagar as notas?', ['c-importacao'], { icone: 'alert', titulo: 'Apagar o balancete?', texto: 'As 412 contas lidas desta empresa serão removidas.', botoes: [...SAIR, { rotulo: 'Apagar', variante: 'btn-primary' }] }),
  janela('jn-preencha', 'Preencha os lançamentos (Configurações › Saídas)', ['c-cadastro'], { icone: 'alert', titulo: 'Preencha os lançamentos', html: 'Com Vendas à vista e à prazo ligado, cada CFOP precisa do lançamento. Faltam <b>3</b> em <b>2 CFOPs</b>.', botoes: [{ rotulo: 'Preencher', variante: 'btn-primary' }] }),
  janela('jn-falta-plano', 'Falta importar o plano de contas (Lançamentos automáticos)', ['c-cadastro'], { icone: 'alert', titulo: 'Falta importar o plano de contas', html: 'Os lançamentos automáticos usam as contas do plano. Vá em Plano de contas e leia um balancete primeiro.', botoes: [{ rotulo: 'Entendi', variante: 'btn-primary' }] }),
  janela('jn-falta-preencher', 'Falta preencher antes de conferir (Verificar por conta)', ['c-verificar'], { icone: 'alert', titulo: 'Falta preencher antes de conferir', html: '• Escolha a conta<br>• Importe o relatório da conta', botoes: [{ rotulo: 'Entendi', variante: 'btn-primary' }] }),
  janela('jn-qual-relatorio', 'Qual relatório você corrigiu? (Verificar por conta)', ['c-verificar'], { icone: 'upload', titulo: 'Qual relatório você corrigiu?', botoes: [...SAIR, { rotulo: 'Conta 70002', variante: 'btn-primary' }, { rotulo: 'Conta 70006', variante: 'btn-primary' }] }),
  janela('jn-limpar', 'Limpar a conferência? (Verificar por conta)', ['c-verificar'], { icone: 'alert', titulo: 'Limpar a conferência?', texto: 'O relatório lido e o resultado dessa conferência serão descartados (nunca são salvos).', botoes: [...SAIR, { rotulo: 'Limpar', variante: 'btn-primary' }] }),
  // Conciliadorzinho
  janela('jn-cancelar-conciliacao', 'Cancelar conciliação? (Conciliadorzinho)', ['z-etapas'], { icone: 'alert', titulo: 'Cancelar conciliação?', texto: 'Os arquivos enviados e as contas informadas serão descartados.', botoes: [...SAIR, { rotulo: 'Cancelar tudo', variante: 'btn-primary' }] }),
  janela('jn-confirmar-extrato', 'Confirmar extrato da bandeira (Conciliadorzinho)', ['z-etapas'], { icone: 'landmark', titulo: 'Confirmar extrato da Cielo', html: 'Foram lidos <b>312 lançamentos</b> em 2 arquivo(s), referentes a: julho e agosto de 2026, na conta 11201. Confirma?', botoes: [{ rotulo: 'Revisar' }, { rotulo: 'Sim, confirmar', variante: 'btn-primary' }] }),
  janela('jn-meses-fora', 'Meses fora do extrato do cartão (Conciliadorzinho)', ['z-etapas'], { icone: 'alert', titulo: 'Meses fora do extrato do cartão', html: 'O arquivo de notas tem <b>setembro</b>, que não está no extrato.', botoes: [{ rotulo: 'Escolher outro arquivo' }, { rotulo: 'Prosseguir mesmo assim', variante: 'btn-primary' }] }),
];
