// Conferência Contábil — Model (packages/core). Só o que é público sai daqui.
export * from './tipos';
export * from './acoes';
export * from './repo';
export { criarRepoConferenciaMemoria } from './repo.memoria';
export { EMPRESAS_EXEMPLO } from './__exemplos__/empresas';
export { CLIENTES, SEED } from './tabelas/clientes';
export { CFOP_DESC } from './tabelas/cfop';
export { SV, SERV_CAT, ehServ, type CategoriaServico, type ConfigServico } from './tabelas/servicos';
export * from './arquivos';
export * from './regras/cfop';
export * from './regras/empresa';
export * from './regras/periodo';
export * from './regras/vendaVista';
export * from './regras/servicos';
export * from './regras/divergencias';
export * from './regras/conciliacao';
export * from './regras/relatorio';
export * from './regras/checklist';
export * from './regras/consulta';
export * from './regras/auditoria';
export * from './regras/importacao';
export * from './regras/lancamentosAuto';
export * from './regras/servicosConferencia';
export * from './regras/verificarConta';
export * from './regras/foraDoPadraoFiscal';
export * from './regras/consultaCsv';
export * from './regras/verificarContaTela';
