// Empresas do escritório: [código do ERP, nome, regime]. Veio da lista CLIENTES da Conferência
// (conferencia.html ~L1515) e agora é de todos os aplicativos do nads.
import type { EmpresaDoEscritorio } from './tipos';

export const EMPRESAS: readonly EmpresaDoEscritorio[] = [
  { codigo: 462, nome: "3M EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Presumido" },
  { codigo: 356, nome: "A7 COMERCIO DE VEICULOS LTDA", regime: "Presumido" },
  { codigo: 515, nome: "A7 MOBILE LTDA", regime: "Simples" },
  { codigo: 591, nome: "AAP INTERMEDIACOES LTDA", regime: "Simples" },
  { codigo: 450, nome: "ACO FORTE METAIS LTDA", regime: "Simples" },
  { codigo: 371, nome: "ACSSP ADM PROMOCAO DE VENDAS LTDA", regime: "Simples" },
  { codigo: 205, nome: "ADEMILSON OLIVEIRA CRUZ", regime: "Simples" },
  { codigo: 66, nome: "ADERLEI DOS SANTOS & CIA LTDA", regime: "Presumido" },
  { codigo: 541, nome: "AGRIENERGY FERTIAGRO LTDA", regime: "Simples" },
  { codigo: 533, nome: "ALINE CARVALHO FELIX MORONI", regime: "Domésticas" },
  { codigo: 279, nome: "ALMEIDA & SOUZA PRODUTOS ALIMENTICIOS LTDA", regime: "Simples" },
  { codigo: 265, nome: "ALTA FLORESTA TRANSPORTES LTDA", regime: "Simples" },
  { codigo: 600, nome: "ALVES CRUZ ACADEMIA PREMIUM LTDA", regime: "Simples" },
  { codigo: 503, nome: "AMPLA SERVICOS DE SAUDE LTDA", regime: "Simples" },
  { codigo: 493, nome: "ANTONIA'S LTDA", regime: "Simples" },
  { codigo: 174, nome: "ARMARINHO E PAPELARIA TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 537, nome: "ARTEFATO ACABAMENTOS LTDA", regime: "Simples" },
  { codigo: 488, nome: "ASSOCIACAO BENEFICENTE GALPAO SOLIDARIO DE LAGOA SECA", regime: "Isentas" },
  { codigo: 536, nome: "ASSOCIAÇÃO COMERCIAL E EMPRESARIAL DE TAIOBEIRAS", regime: "Isentas" },
  { codigo: 342, nome: "ASSOCIACAO DE MULHERES EM PROL DO DESENVOLVIMENTO DE RI", regime: "Isentas" },
  { codigo: 394, nome: "AURORA REFLORESTAMENTO E TRANSPORTES LTDA", regime: "Simples" },
  { codigo: 395, nome: "AURORA REFLORESTAMENTO E TRANSPORTES LTDA - FILIAL 02", regime: "Simples" },
  { codigo: 432, nome: "AURORA REFLORESTAMENTO E TRANSPORTES LTDA - FILIAL 03", regime: "Simples" },
  { codigo: 231, nome: "AUTO GIRO PECAS E ACESSORIOS LTDA", regime: "Simples" },
  { codigo: 481, nome: "B LIMA SERVICOS MEDICOS LTDA", regime: "Simples" },
  { codigo: 470, nome: "BALAO MAGICO KIDS LTDA", regime: "Simples" },
  { codigo: 581, nome: "BC SAUDE LTDA", regime: "Simples" },
  { codigo: 575, nome: "BDV LTDA", regime: "Presumido" },
  { codigo: 86, nome: "BIBOKA EMBALAGENS LTDA", regime: "Simples" },
  { codigo: 599, nome: "BIBOKA EMBALAGENS LTDA - FILIAL", regime: "Simples" },
  { codigo: 96, nome: "BIG LANCHES DE TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 207, nome: "BMJ SOM AUTOMOTIVO LTDA", regime: "Simples" },
  { codigo: 79, nome: "BN ELETRODOMESTICOS LTDA", regime: "Simples" },
  { codigo: 145, nome: "BN ELETRODOMESTICOS LTDA", regime: "Simples" },
  { codigo: 549, nome: "BOOZE PUB LTDA", regime: "Simples" },
  { codigo: 250, nome: "BRASAO INDUSTRIA FLORESTAL LTDA", regime: "Simples" },
  { codigo: 568, nome: "BRAZILIAN COFFEE LTDA", regime: "Real" },
  { codigo: 413, nome: "BRAZILIAN FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Real" },
  { codigo: 414, nome: "BRAZILIAN FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Real" },
  { codigo: 418, nome: "BRAZILIAN FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA - FILIAL 03", regime: "Real" },
  { codigo: 453, nome: "BRAZILIAN FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA - FILIAL 04", regime: "Real" },
  { codigo: 526, nome: "C&R ESCOLA DE IDIOMAS LTDA", regime: "Simples" },
  { codigo: 577, nome: "CAFE RENASCER SPE LTDA", regime: "Real" },
  { codigo: 494, nome: "CAIXA ESCOLAR JOVITA SECUNDINA REGO", regime: "Isentas" },
  { codigo: 560, nome: "CAMARA DE DIRIGENTES LOJISTAS DE TAIOBEIRAS", regime: "Isentas" },
  { codigo: 555, nome: "CARLOS LUCAS MENDES - FAZ UNIÃO", regime: "Física" },
  { codigo: 226, nome: "CARLOS LUCAS MENDES - FAZ. GAMELEIRA", regime: "Física" },
  { codigo: 62, nome: "CARLOS LUCAS MENDES - FAZ. TABATINGA", regime: "Física" },
  { codigo: 228, nome: "CARLOS LUCAS MENDES - SAO JOSE", regime: "Física" },
  { codigo: 467, nome: "CATVAN TECNOLOGIA LTDA", regime: "Simples" },
  { codigo: 101, nome: "CAULIM ALVES DE SOUZA LTDA", regime: "Simples" },
  { codigo: 455, nome: "CENTRO DE ODONTOLOGIA E SAUDE DE TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 463, nome: "CENTRO DE ODONTOLOGIA ESTETICA LTDA", regime: "Simples" },
  { codigo: 15, nome: "CERAMICA FORTALEZA LTDA", regime: "Simples" },
  { codigo: 501, nome: "CERAMICA FORTALEZA LTDA - FILIAL", regime: "Simples" },
  { codigo: 81, nome: "CERAMICA MINAS FORTE LTDA", regime: "Simples" },
  { codigo: 368, nome: "CERAMICA MINAS FORTE LTDA - FILIAL 02", regime: "Simples" },
  { codigo: 183, nome: "CLEIA CRUZ DE OLIVEIRA - CPF 033.911.646.38", regime: "Simples" },
  { codigo: 597, nome: "CONSTRU UNIAO MATERIAIS DE CONSTRUCAO LTDA", regime: "Simples" },
  { codigo: 175, nome: "CONSTRU-G MIRANDA MATERIAIS DE CONSTRUCAO LTDA", regime: "Simples" },
  { codigo: 552, nome: "CONSTRULAR MATERIAIS DE PINTURA E CONSTRUCAO LTDA", regime: "Simples" },
  { codigo: 434, nome: "CONSTRUNOVO LTDA", regime: "Simples" },
  { codigo: 593, nome: "CONSTRUTOP MATERIAIS DE CONSTRUCAO LTDA", regime: "Simples" },
  { codigo: 468, nome: "CONSTRUTORA E INCORPORADORA OURO VERDE LTDA", regime: "Simples" },
  { codigo: 540, nome: "CREATIVE COMPANY LTDA", regime: "Simples" },
  { codigo: 589, nome: "CREATIVE DIGITAL LTDA", regime: "Simples" },
  { codigo: 286, nome: "CRIATIVA EDUCACAO E TREINAMENTO LTDA", regime: "Simples" },
  { codigo: 287, nome: "CRIATIVA PRESTACOES DE SERVICOS EDUCACIONAIS LTDA", regime: "Simples" },
  { codigo: 285, nome: "CRUZ E COELHO SERVICOS MEDICOS LTDA", regime: "Simples" },
  { codigo: 519, nome: "DARLENE DE FREITAS C VOLPONI LTDA", regime: "Simples" },
  { codigo: 546, nome: "DERACI JOSE DE OLIVEIRA", regime: "Física" },
  { codigo: 547, nome: "DERACI JOSE DE OLIVEIRA", regime: "Física" },
  { codigo: 565, nome: "DJALMA MOREIRA DE AGUIAR", regime: "Simples" },
  { codigo: 332, nome: "DOMINGA ROSA GOMES 06371828630", regime: "Simples" },
  { codigo: 10, nome: "DORNAS HAVANA LTDA", regime: "Simples" },
  { codigo: 510, nome: "DOUGLAS AUTO CENTER LTDA", regime: "Simples" },
  { codigo: 407, nome: "DUDA HOME DE TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 421, nome: "D´FARMA FARMACIA DE MANIPULACAO LTDA", regime: "Simples" },
  { codigo: 177, nome: "EDSON FREITAS LIMA", regime: "Domésticas" },
  { codigo: 578, nome: "ELITE HIDRAULICA E SOLDAS LTDA", regime: "Simples" },
  { codigo: 606, nome: "EMILLY MARQUES ARQUITETURA LTDA", regime: "Simples" },
  { codigo: 313, nome: "EMPORIO DAS CARNES LTDA", regime: "Simples" },
  { codigo: 583, nome: "EMPORIO VERDE DISTRIBUIDORA LTDA", regime: "Simples" },
  { codigo: 345, nome: "EMPREENDIMENTO OLIVEIRA E COSTA LTDA", regime: "Simples" },
  { codigo: 584, nome: "EMPREENDIMENTOS IMOBILIARIOS M&A LTDA", regime: "Presumido" },
  { codigo: 563, nome: "EVANDRO DE CASTRO", regime: "Física" },
  { codigo: 499, nome: "FARLEN XAVIER SANTOS 36075344896", regime: "MEI" },
  { codigo: 506, nome: "FAST EMPREENDIMENTOS AERONAUTICO LTDA", regime: "Presumido" },
  { codigo: 542, nome: "FELIPE ANDRADE ACADEMIA ESPECIALIZADA LTDA", regime: "Simples" },
  { codigo: 543, nome: "FELIPE ANDRADE ACADEMIA ESPECIALIZADA LTDA", regime: "Simples" },
  { codigo: 309, nome: "FITO ALIMENTOS LTDA", regime: "Simples" },
  { codigo: 292, nome: "FITO INDUSTRIA E COMERCIO DE ALIMENTOS LTDA", regime: "Presumido" },
  { codigo: 137, nome: "FLORENCIO MENDES DE OLIVEIRA", regime: "Física" },
  { codigo: 179, nome: "FLORENCIO MENDES DE OLIVEIRA", regime: "Física" },
  { codigo: 23, nome: "FLORENCIO MENDES DE OLIVEIRA LTDA", regime: "Simples" },
  { codigo: 147, nome: "FLORENCIO MENDES DE OLIVEIRA LTDA - FILIAL 04", regime: "Simples" },
  { codigo: 396, nome: "FLOROCARV REFLORESTAMENTO E TRANSPORTES LTDA", regime: "Simples" },
  { codigo: 611, nome: "FRANCIELLE SILVA SANTANA", regime: "Domésticas" },
  { codigo: 572, nome: "FREEDOM REFORESTING LTDA", regime: "Presumido" },
  { codigo: 582, nome: "FREEDOM REFORESTING LTDA", regime: "Presumido" },
  { codigo: 465, nome: "FSS SERVICOS MEDICOS LTDA", regime: "Simples" },
  { codigo: 291, nome: "G.A.S SAUDE DE DIVISA ALEGRE LTDA", regime: "Simples" },
  { codigo: 277, nome: "G.A.S SERVICOS LABORATORIAIS LTDA", regime: "Simples" },
  { codigo: 521, nome: "GALDUS PROJETOS INDUSTRIAIS LTDA", regime: "Simples" },
  { codigo: 444, nome: "GALPAO VEICULOS E LOCADORA LTDA", regime: "Presumido" },
  { codigo: 610, nome: "GAS TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 562, nome: "GERLANE ALVES SOARES", regime: "Simples" },
  { codigo: 525, nome: "GILDO FARIA", regime: "Física" },
  { codigo: 527, nome: "GL MATERIAIS DE CONSTRUCAO LTDA", regime: "Simples" },
  { codigo: 553, nome: "GLM ODONTOLOGIA LTDA", regime: "Simples" },
  { codigo: 448, nome: "GRANMIX COMERCIO DE ALIMENTOS LTDA - FILIAL 02", regime: "Simples" },
  { codigo: 449, nome: "GRANMIX COMERCIO DE ALIMENTOS LTDA - MATRIZ", regime: "Simples" },
  { codigo: 83, nome: "GRIFFIN ARTIGOS DO VESTUARIO E ACESSORIOS LTDA", regime: "Simples" },
  { codigo: 363, nome: "GS EMPREENDIMENTOS COMERCIAIS LTDA", regime: "Simples" },
  { codigo: 433, nome: "GUGA INDUSTRIA & COMERCIO DE RACAO ANIMAL LTDA", regime: "Simples" },
  { codigo: 423, nome: "GUGA INDUSTRIA & COMERCIO DE RACAO ANIMAL LTDA", regime: "Simples" },
  { codigo: 576, nome: "GUIMARAES E SILVA INSTITUTO INTEGRADO LTDA", regime: "Simples" },
  { codigo: 544, nome: "HELLO NUTRITION COMERCIO DE ALIMENTOS E BEBIDAS LTDA", regime: "Simples" },
  { codigo: 545, nome: "HELLO NUTRITION COMERCIO DE ALIMENTOS E BEBIDAS LTDA", regime: "Simples" },
  { codigo: 564, nome: "HELLO NUTRITION COMERCIO DE ALIMENTOS E BEBIDAS LTDA - FILIAL", regime: "Simples" },
  { codigo: 592, nome: "HERMES REFLORESTAMENTO E TRANSPORTE LTDA", regime: "Simples" },
  { codigo: 594, nome: "HERMES REFLORESTAMENTO E TRANSPORTE LTDA - FILIAL", regime: "Simples" },
  { codigo: 598, nome: "IMPERIO DAS PIZZAS TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 393, nome: "INFANCY SERVICOS PEDIATRICOS LTDA", regime: "Simples" },
  { codigo: 152, nome: "JANIO JOSE DE ALMEIDA", regime: "Simples" },
  { codigo: 425, nome: "JOELFLOR PEREIRA DA ROCHA - DOMÉSTICA", regime: "Domésticas" },
  { codigo: 424, nome: "JOELFLOR PEREIRA DA ROCHA - FAZENDA", regime: "Física" },
  { codigo: 181, nome: "JOSE MENDES FREITAS", regime: "Física" },
  { codigo: 548, nome: "JOSIEL GOMES ARRUDA SPOSITO E OUTRO", regime: "Física" },
  { codigo: 412, nome: "KOPEK FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Presumido" },
  { codigo: 389, nome: "LATORRES DISTRIBUIDORA LTDA", regime: "Simples" },
  { codigo: 415, nome: "LAVICA EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Presumido" },
  { codigo: 416, nome: "LAVICA EMPREENDIMENTOS FLORESTAIS LTDA - FILIAL 02", regime: "Presumido" },
  { codigo: 474, nome: "LC FLORESTAL LTDA", regime: "Presumido" },
  { codigo: 586, nome: "LC SERVICOS AGRICOLAS E FLORESTAIS LTDA", regime: "Simples" },
  { codigo: 380, nome: "LEONARDO MENDES MARQUES LTDA", regime: "Presumido" },
  { codigo: 326, nome: "LEONEL RODRIGUES REPRESENTACOES LTDA", regime: "Simples" },
  { codigo: 505, nome: "LISA COSTA AME LTDA", regime: "Simples" },
  { codigo: 601, nome: "LIZZ SHOW'S LTDA", regime: "Simples" },
  { codigo: 605, nome: "LL CENTRO ESTETICO LTDA", regime: "Simples" },
  { codigo: 457, nome: "LOCADORA DANUBIO AZUL LTDA", regime: "Simples" },
  { codigo: 37, nome: "LOTERIAS FREITAS & MENDES LTDA", regime: "Simples" },
  { codigo: 249, nome: "LOTERIAS TAIOBEIRAS LTDA", regime: "Simples" },
  { codigo: 580, nome: "LUCAS MENDES FILHO MARQUES SUCUPIRA", regime: "Física" },
  { codigo: 314, nome: "M A REFLORESTAMENTO E TRANSPORTES LTDA", regime: "Simples" },
  { codigo: 40, nome: "MADEIREIRA E MARCENARIA MIRANDA LTDA", regime: "Simples" },
  { codigo: 489, nome: "MARISFRUTAS LTDA", regime: "Simples" },
  { codigo: 479, nome: "ME ATACADO LTDA", regime: "Simples" },
  { codigo: 65, nome: "MERCEARIA LAGOA GRANDE LTDA", regime: "Simples" },
  { codigo: 528, nome: "MIKAEL DOUGLAS A DE OLIVEIRA", regime: "Simples" },
  { codigo: 411, nome: "MINAS FORESTRY EMPREENDIMENTOS FLORESTAIS LTDA", regime: "Presumido" },
  { codigo: 477, nome: "MINAS MAIS VARIEDADES LTDA", regime: "Simples" },
  { codigo: 236, nome: "MINIMERCADO SANTO EXPEDITO LTDA", regime: "Simples" },
  { codigo: 358, nome: "MITRA TRANSPORTES E SERVICOS LTDA", regime: "Presumido" },
  { codigo: 359, nome: "MITRA TRANSPORTES E SERVICOS LTDA", regime: "Presumido" },
  { codigo: 257, nome: "MODELO TRANSPORTES E SERVICOS LTDA", regime: "Simples" },
  { codigo: 310, nome: "MOR LABORATORIO NUTRICIONAL LTDA", regime: "Simples" },
  { codigo: 579, nome: "MORONI & XAVIER AUTOPECAS LTDA", regime: "Simples" },
  { codigo: 585, nome: "MORONI & XAVIER AUTOPECAS LTDA - FILIAL", regime: "Simples" },
  { codigo: 551, nome: "MURILLO MENDES DE OLIVEIRA", regime: "Simples" },
  { codigo: 595, nome: "NERES EMPREENDIMENTOS LTDA", regime: "Simples" },
  { codigo: 284, nome: "NILMA CONTABILIDADE LTDA", regime: "Simples" },
  { codigo: 514, nome: "OLARIA E TRANSPORTES TK LTDA", regime: "Simples" },
  { codigo: 604, nome: "OLARIA K&K LTDA", regime: "Simples" },
  { codigo: 43, nome: "ORGANIZACAO ALVES & ARAUJO CONFECCOES LTDA", regime: "Simples" },
  { codigo: 381, nome: "ORGANIZACOES FURTADO LTDA", regime: "Simples" },
  { codigo: 596, nome: "ORGANIZACOES FURTADO LTDA - FILIAL", regime: "Simples" },
  { codigo: 348, nome: "ORGANIZACOES JG LTDA", regime: "Simples" },
  { codigo: 388, nome: "ORGANIZACOES PINK BIJOUX LTDA", regime: "Simples" },
  { codigo: 441, nome: "OURO PRETO REFLORESTAMENTOS LTDA", regime: "Presumido" },
  { codigo: 408, nome: "OURO VERDE MINERACAO LTDA", regime: "Presumido" },
  { codigo: 409, nome: "OURO VERDE MINERACAO LTDA - FILIAL 02", regime: "Presumido" },
  { codigo: 452, nome: "OURO VERDE MINERACAO LTDA - FILIAL 04", regime: "Presumido" },
  { codigo: 476, nome: "OURO VERDE MINERACAO LTDA - FILIAL 05", regime: "Presumido" },
  { codigo: 509, nome: "OURO VERDE MINERACAO LTDA - FILIAL 06", regime: "Presumido" },
  { codigo: 458, nome: "PABLO RAMON MENDES FREITAS", regime: "Domésticas" },
  { codigo: 191, nome: "PEDRO JORGE SANTOS SOUZA", regime: "Física" },
  { codigo: 49, nome: "POSTO DE COMBUSTIVEIS ALTA FLORESTA LTDA", regime: "Presumido" },
  { codigo: 429, nome: "POSTO DE COMBUSTIVEIS ANDRIELE LIMITADA", regime: "Presumido" },
  { codigo: 237, nome: "POSTO DE COMBUSTIVEIS BERIZAL LTDA", regime: "Presumido" },
  { codigo: 559, nome: "POSTO DE COMBUSTIVEIS JM JOAO MANOEL II LTDA", regime: "Presumido" },
  { codigo: 532, nome: "POUSADA, RESTAURANTE E PANIFICADORA JM- JOAO MANOEL LTDA", regime: "Simples" },
  { codigo: 508, nome: "PRIME ESTETICA AVANCADA LTDA", regime: "Simples" },
  { codigo: 550, nome: "PRIME FISIOTERAPIA E CONSULTORIOS MEDICOS ESPECIAL", regime: "Simples" },
  { codigo: 343, nome: "RAIZZ EMPORIO DA SAUDE LTDA", regime: "Simples" },
  { codigo: 569, nome: "RDS AGREGADOS & LOGISTICA LTDA", regime: "Simples" },
  { codigo: 307, nome: "REGINALDA PEREIRA DA SILVA SOUSA 14920571690", regime: "Simples" },
  { codigo: 558, nome: "RENALD C FILHO & CIA LTDA", regime: "Simples" },
  { codigo: 252, nome: "RENALD DA CRUZ FILHO LIMITADA", regime: "Simples" },
  { codigo: 50, nome: "ROSA MENDES DE OLIVEIRA CORBELLI LTDA", regime: "Simples" },
  { codigo: 51, nome: "ROSILENE MARQUES MARTINS", regime: "Simples" },
  { codigo: 149, nome: "ROSILENE MARQUES MARTINS  - FILIAL", regime: "Simples" },
  { codigo: 353, nome: "SAMIR LUCAS MENDES", regime: "Física" },
  { codigo: 573, nome: "SCP-VIVEIRO RENASCER", regime: "Presumido" },
  { codigo: 311, nome: "SELMA SIMONELLY DA SILVA PEREIRA 84343540634", regime: "MEI" },
  { codigo: 538, nome: "SENA PARTICIPACOES LTDA", regime: "Simples" },
  { codigo: 54, nome: "SERRALHERIA OURO VERDE LTDA", regime: "Simples" },
  { codigo: 347, nome: "SILVANDE AUGUSTO MIRANDA", regime: "Física" },
  { codigo: 366, nome: "SOLUS REFLORESTAMENTO LTDA", regime: "Simples" },
  { codigo: 561, nome: "SOMA NEGOCIOS E INTERMEDIACOES FINANCEIRAS LTDA", regime: "Simples" },
  { codigo: 446, nome: "SPIROU CONSULTORIA E INVESTIMENTOS LTDA", regime: "Presumido" },
  { codigo: 443, nome: "SU SEDUCAO MODA INTIMA LTDA", regime: "Simples" },
  { codigo: 360, nome: "SUPERMERCADO CENTRAL DE BARREIROS LTDA", regime: "Simples" },
  { codigo: 80, nome: "TECNOAGRO PROJETOS E CONSULTORIA LTDA", regime: "Simples" },
  { codigo: 298, nome: "TEOBALDO MENDES DE OLIVEIRA LTDA", regime: "Simples" },
  { codigo: 299, nome: "TEOBALDO MENDES DE OLIVEIRA LTDA - FILIAL 02", regime: "Simples" },
  { codigo: 300, nome: "TEOBALDO MENDES DE OLIVEIRA LTDA - FILIAL 03", regime: "Simples" },
  { codigo: 301, nome: "TEOBALDO MENDES DE OLIVEIRA LTDA - FILIAL 04", regime: "Simples" },
  { codigo: 496, nome: "TIAGO SANTOS DE SOUZA", regime: "Simples" },
  { codigo: 590, nome: "TORIBA TECNOLOGIA E GESTAO EMPRESARIAL LTDA", regime: "Simples" },
  { codigo: 58, nome: "TORNEARIA VOLPONI INDUSTRIA E COMERCIO LTDA", regime: "Simples" },
  { codigo: 55, nome: "TORRA TORRA LTDA", regime: "Simples" },
  { codigo: 461, nome: "UNIVERSO CENTRO DE EDUCACAO INFANTIL LTDA", regime: "Simples" },
  { codigo: 269, nome: "VALDELICE ROCHA ALMEIDA", regime: "Domésticas" },
  { codigo: 6, nome: "VANDERLEI RUFINO DOS SANTOS", regime: "Física" },
  { codigo: 362, nome: "VERA LUCIA DE OLIVEIRA", regime: "Simples" },
  { codigo: 417, nome: "VERA REFLORESTAMENTOS LTDA", regime: "Simples" },
  { codigo: 492, nome: "VERSATIL LTDA", regime: "Simples" },
  { codigo: 482, nome: "VICTOR ARAUJO SERVICOS MEDICOS LTDA", regime: "Simples" },
  { codigo: 232, nome: "VICTOR GOMES ARRUDA SPOSITO", regime: "Física" },
  { codigo: 511, nome: "VISUAL KIDS LTDA", regime: "Simples" },
  { codigo: 567, nome: "VIVEIRO RENASCER LTDA", regime: "Presumido" },
  { codigo: 288, nome: "VOLPONI COMERCIO DE ACESSORIOS LTDA", regime: "Simples" },
  { codigo: 571, nome: "VOLPONI CONSTRUCOES MECANICAS INDUSTRIA E COMERCIO", regime: "Simples" },
  { codigo: 289, nome: "VOLPONI INDUSTRIA MECANICA LTDA", regime: "Simples" },
  { codigo: 367, nome: "VS AGROFLORESTAL LTDA", regime: "Presumido" },
  { codigo: 486, nome: "VS MEDICINA ESPECIALIZADA LTDA", regime: "Simples" },
  { codigo: 502, nome: "VSPOSITO SERVICOS MEDICOS LTDA", regime: "Simples" },
  { codigo: 603, nome: "WB SUSHI LTDA", regime: "Simples" },
  { codigo: 466, nome: "WR SERVICOS FLORESTAIS LTDA", regime: "Presumido" },
  { codigo: 485, nome: "XTREME ACADEMIA ESPECIALIZADA LTDA", regime: "Simples" },
  { codigo: 608, nome: "ZELO AGROINDUSTRIAS LTDA - FILIAL C. SALES", regime: "Simples" },
  { codigo: 609, nome: "ZELO AGROINDUSTRIAS LTDA - FILIAL SJP", regime: "Simples" },
  { codigo: 607, nome: "ZELO AGROINDUSTRIAS LTDA - FILIAL TAIOBEIRAS", regime: "Simples" },
  { codigo: 602, nome: "ZELO AGROINDUSTRIAS LTDA - MATRIZ", regime: "Simples" },
];
